# Generated by Django 3.1 on 2020-08-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caesar_cipher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalword',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='capitalword',
            name='word',
            field=models.TextField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistic',
            name='uri',
            field=models.TextField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
